src/Entity/Post.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;


/**
 * @ORM\Entity(repositoryClass="App\Repository\PostRepository")
 */
class Post
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $comment_cant;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="El campo Titulo no puede estar vacío")
     * @Assert\Length(
     *     min=4,
     *     exactMessage="El título debe tener como mínimo 4 caracteres"
     * )
     */
    private $titulo;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="El campo Imagen no puede estar vacío")
     * @Assert\File(mimeTypes={"image/png", "image/jpeg"})
     */
    private $imagen;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="El campo Texto no puede estar vacío")
     */
    private $texto;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $tipo;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\NotBlank(message="El campo Password no puede estar vacío")
     * @Assert\GreaterThan(
     *     value = 2
     * )
     */
    private $aforo;

    /**
     * @ORM\Column(type="datetime")
     */
    private $fecha;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="posts")
     * @ORM\JoinColumn()
     */
    private $user;

    /**
     * @ORM\Column(type="boolean")
     */
    private $visible;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Inscripciones", mappedBy="post")
     */
    private $inscripciones;

    public function __construct()
    {
        $this->inscripciones = new ArrayCollection();
    }

    /**
     * @return mixed
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param mixed $user
     * @return Post
     */
    public function setUser($user)
    {
        $this->user = $user;
        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCommentCant(): ?int
    {
        return $this->comment_cant;
    }

    public function setCommentCant(int $comment_cant): self
    {
        $this->comment_cant = $comment_cant;

        return $this;
    }

    public function getTitulo(): ?string
    {
        return $this->titulo;
    }

    public function setTitulo(string $titulo): self
    {
        $this->titulo = $titulo;

        return $this;
    }

    public function getImagen()
    {
        return $this->imagen;
    }

    public function setImagen($imagen)
    {
        $this->imagen = $imagen;

        return $this;
    }

    public function getTexto(): ?string
    {
        return $this->texto;
    }

    public function setTexto(string $texto): self
    {
        $this->texto = $texto;

        return $this;
    }

    public function getTipo(): ?string
    {
        return $this->tipo;
    }

    public function setTipo(string $tipo): self
    {
        $this->tipo = $tipo;

        return $this;
    }

    public function getAforo(): ?int
    {
        return $this->aforo;
    }

    public function setAforo(?int $aforo): self
    {
        $this->aforo = $aforo;

        return $this;
    }

    public function getFecha()
    {
        return $this->fecha;
    }

    public function setFecha($fecha)
    {
        $this->fecha = $fecha;

        return $this;
    }

    public function getVisible(): ?bool
    {
        return $this->visible;
    }

    public function setVisible(bool $visible): self
    {
        $this->visible = $visible;

        return $this;
    }

    public function getUrlImagen()
    {
        return '/images/gallery/'.$this->getImagen();
    }

    /**
     * @return Collection|Inscripciones[]
     */
    public function getInscripciones(): Collection
    {
        return $this->inscripciones;
    }

    public function addInscripcione(Inscripciones $inscripcione): self
    {
        if (!$this->inscripciones->contains($inscripcione)) {
            $this->inscripciones[] = $inscripcione;
            $inscripcione->setPost($this);
        }

        return $this;
    }

    public function removeInscripcione(Inscripciones $inscripcione): self
    {
        if ($this->inscripciones->contains($inscripcione)) {
            $this->inscripciones->removeElement($inscripcione);
            // set the owning side to null (unless already changed)
            if ($inscripcione->getPost() === $this) {
                $inscripcione->setPost(null);
            }
        }

        return $this;
    }
}

src/Form/PostType.php
<?php

namespace App\Form;

use App\Entity\Post;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('titulo', TextType::class)
            ->add('imagen', FileType::class)
            ->add('texto', TextareaType::class)
            ->add('tipo', ChoiceType::class, [
                'choices' => [
                    'ELIGE UNA OPCION' => 'EVENTO_GENERICO',
                    'EVENTO GENERICO' => 'EVENTO_GENERICO',
                    'EVENTO COSPLAY' => 'EVENTO_COSPLAY',
                    'EVENTO PELÍCULA' => 'EVENTO_PELICULA',
                    'EVENTO REUNION' => 'EVENTO_REUNION',
                    'EVENTO COMIDA' => 'EVENTO_COMIDA'
                ]
        ])
            ->add('aforo', IntegerType::class)
            ->add('fecha', DateTimeType::class, [
                'format' => 'yyyy HH:mm:ss dd-MM',
                'input'  => 'datetime',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Post::class,
        ]);
    }
}

src/Controller/PostController.php
<?php

namespace App\Controller;

use App\Entity\Post;
use App\Entity\User;
use App\Form\PostType;
use App\Helper\FileUploader;
use App\Repository\PostRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class PostController extends AbstractController
{
    /**
     * @Route("/", name="index", methods={"GET"})
     */
    public function indexAbsolute(PostRepository $postRepository): Response
    {
        $posts = $postRepository->findAll();

        return $this->render('index.html.twig', [
            'posts' => $posts,
            'error' => null
        ]);
    }

    /**
     * @Security("has_role('ROLE_ADMIN')")
     * @Route("/post", name="post_index", methods={"GET"})
     */
    public function index(PostRepository $postRepository): Response
    {
        $posts = $postRepository->findAll();

        return $this->render('post/index.html.twig', [
            'posts' => $posts,
            'error' => null
        ]);
    }

    /**
     * @Route("/filter", name="filter_inicio", methods={"GET", "POST"})
     */
    public function filtrarInicio(PostRepository $postRepository, Request $request)
    {
        $fecha1 = $request->request->get('fecha1');
        $fecha2 = $request->request->get('fecha2');
        $tipo = $request->request->get('tipo');
        $texto = $request->request->get('texto');
        $posts = $postRepository->filtrosComplejosInicio($fecha1, $fecha2, $tipo, $texto);

        return $this->render('index.html.twig', [
            'posts' => $posts,
            'error' => 'Filtrando'
        ]);
    }

    /**
     * @Security("has_role('ROLE_USER')")
     * @Route("/post/filter", name="post_filter", methods={"GET", "POST"})
     */
    public function filtrar(PostRepository $postRepository, Request $request)
    {
        $fecha1 = $request->request->get('fecha1');
        $fecha2 = $request->request->get('fecha2');
        $tipo = $request->request->get('tipo');
        $texto = $request->request->get('texto');
        $usuario = $this->getUser();
        $posts = $postRepository->filtrarInicio($fecha1, $fecha2, $tipo, $texto, $usuario);


        return $this->render('post/index.html.twig', [
            'posts' => $posts,
            'error' => 'Filtrando'
        ]);
    }

    /**
     * @Route("/filter/{id}", name="filter_absolute", methods={"GET", "POST"})
     */
    public function filtrarAbsolute(PostRepository $postRepository, Request $request, User $user)
    {
        if ($user)
        {
            $filtroUser = $user;
        }
        else
        {
            $filtroUser = $this->getUser() ?? null;
        }
        $fecha1 = $request->request->get('fecha1');
        $fecha2 = $request->request->get('fecha2');
        $tipo = $request->request->get('tipo');
        $texto = $request->request->get('texto');
        $usuario = $filtroUser;
        $posts = $postRepository->filtrosComplejos($fecha1, $fecha2, $tipo, $texto, $usuario);

        return $this->render('index.html.twig', [
            'posts' => $posts,
            'error' => 'Filtrando'
        ]);
    }

    /**
     * @Security("has_role('ROLE_USER')")
     * @Route("/post/new", name="post_new", methods={"GET","POST"})
     */
    public function new(Request $request, FileUploader $fileUploader): Response
    {
        $post = new Post();
        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var UploadedFile $imagen */
            $imagen = $post->getImagen();

            $fileName = $fileUploader->upload($imagen);
            $post->setImagen($fileName);

            $post->setUser($this->getUser());
            $post->setCommentCant(0);
            $post->setVisible(true);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($post);
            $entityManager->flush();

            return $this->redirectToRoute('post_index');
        }

        return $this->render('post/new.html.twig', [
            'post' => $post,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/post/{id}", name="post_show", methods={"GET"})
     */
    public function show(Post $post): Response
    {
        return $this->render('post/show.html.twig', [
            'post' => $post,
        ]);
    }

    /**
     * @Route("/post/{id}/edit", name="post_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Post $post, FileUploader $fileUploader): Response
    {
        $post->setImagen(new File(
            $this->getParameter('images_directory').'/'.$post->getImagen()));

        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var UploadedFile $imagen */
            $imagen = $post->getImagen();

            $fileName = $fileUploader->upload($imagen);
            $post->setImagen($fileName);

            $this->getDoctrine()->getManager()->flush();
            return $this->redirectToRoute('post_index', [
                'id' => $post->getId(),
            ]);
        }

        return $this->render('post/edit.html.twig', [
            'post' => $post,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/post/{id}", name="post_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Post $post): Response
    {
        if ($this->isCsrfTokenValid('delete'.$post->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($post);
            $entityManager->flush();
        }

        return $this->redirectToRoute('post_index');
    }

    public function montarQueryFiltrado()
    {

    }
}

templates/post/_delete_form.html.twig
<form class="espacio-pequeño" method="post" action="{{ path('post_delete', {'id': post.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ post.id) }}">
    <button class="btn btn-warning">Delete</button>
</form>

templates/post/_form.html.twig
    {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
    <div class="text-danger mb-3">
        {{ form_errors(form.titulo, {'attr': {'class': 'text-danger mb-3'}}) }}
    </div>
    {{ form_label(form.titulo) }}
    {{ form_widget(form.titulo, {'attr': {'class': 'form-control'}}) }}
    <div class="text-danger mb-3">
        {{ form_errors(form.texto, {'attr': {'class': 'text-danger mb-3'}}) }}
    </div>
    {{ form_label(form.texto) }}
    {{ form_widget(form.texto, {'attr': {'class': 'form-control'}}) }}
    <div class="text-danger mb-3">
        {{ form_errors(form.imagen, {'attr': {'class': 'text-danger mb-3'}}) }}
    </div>
    {{ form_label(form.texto) }}
    {{ form_widget(form.imagen, {'attr': {'class': 'form-control'}}) }}
    <div class="text-danger mb-3">
        {{ form_errors(form.tipo, {'attr': {'class': 'text-danger mb-3'}}) }}
    </div>
    {{ form_label(form.tipo) }}
    {{ form_widget(form.tipo, {'attr': {'class': 'form-control'}}) }}
    <div class="text-danger mb-3">
        {{ form_errors(form.aforo, {'attr': {'class': 'text-danger mb-3'}}) }}
    </div>
    {{ form_label(form.aforo) }}
    {{ form_widget(form.aforo, {'attr': {'class': 'form-control'}}) }}
    <div class="text-danger mb-3">
        {{ form_errors(form.fecha, {'attr': {'class': 'text-danger mb-3'}}) }}
    </div>
    {{ form_label(form.fecha) }}
    {{ form_widget(form.fecha, {'attr': {'class': ''}}) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
    {{ form_end(form) }}

templates/post/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Post{% endblock %}

{% block body %}
    <div class="container">
        <h1>Edit the Post</h1>
        <section class="blog-page">
            <div class="container">
                <div class="row">
                    {% block ruta %}
                        <div class="jumbotron">
                            <div class="text-danger">
                                Show post - {{ parent() }}
                            </div>
                        </div>
                    {% endblock %}
                    <div class="col-sm-8">

                        {{ include('post/_form.html.twig', {'button_label': 'Update'}) }}

                        <a href="{{ path('post_index') }}">back to list</a>

                        {{ include('post/_delete_form.html.twig') }}

                    </div>
                </div>
            </div>
        </section>
    </div>
{% endblock %}

templates/post/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Post index{% endblock %}

{% block body %}
    <section class="blog-page">
        <div class="container">
            <nav class="navbar navbar-light bg-light">
                <div class="col-sm-8">
                    <form class="form-group"
                          action="{{ path('post_filter') }}"
                          method="POST"
                          enctype="multipart/form-data">
                        <h3>Aply filters for better results: </h3>
                        <p>Set both dates to search between...</p>
                        <div class="row">
                            <div class="col-sm-5">
                                <label for="fecha1">Find Later Dates: </label>
                                <input class="form-control mr-sm-1" type="date" aria-label="Search" name="fecha1">
                            </div>
                            <div class="col-sm-5">
                                <label for="fecha2">Find Previous Dates: </label>
                                <input class="form-control mr-sm-1" type="date" aria-label="Search" name="fecha2">
                            </div>
                        </div>
                        <label for="tipo">Type of Event:</label>
                        <select name="tipo" class="mr-sm-3">
                            <option value='EVENTO_GENERICO'>GENERIC EVENT</option>
                            <option value="EVENTO COSPLAY">COSPLAY EVENT</option>
                            <option value='EVENTO_PELICULA'>FILM EVENT</option>
                            <option value='EVENTO_REUNION'>EVENT STAY OFF</option>
                            <option value='EVENTO_COMIDA'>EVENT FOOD WAR</option>
                        </select>
                        <div class="form-group">
                            <label for="content">Content on the title: </label>
                            <input class="form-control mr-sm-1" type="text" aria-label="Search" name="texto">
                        </div>
                        <a class="btn btn-secondary" href="{{ path('post_index') }}" role="button" id="DropFilter">Drop Filter</a>
                        <button class="btn btn-danger" type="submit">Apply Filter</button>
                    </form>
                    {% if error %}
                    <div class="row">
                        <div class="alert alert-danger" role="alert">
                            {{ error }}
                        </div>
                    </div>
                    {% endif %}
                </div>
            </nav>
        </div>
    </section>

        <table class="table">
            <thead>
                <tr>
                    <th>Imagen</th>
                    <th>Id</th>
                    <th>UserName</th>
                    <th>Comment_cant</th>
                    <th>Titulo</th>
                    <th>Texto</th>
                    <th>Tipo</th>
                    <th>Aforo</th>
                    <th>Inscripciones</th>
                    <th>Fecha</th>
                    <th>Visible</th>
                    <th>actions</th>
                </tr>
            </thead>
            <tbody>
            {% for post in posts %}
                <tr>
                    <td><img style="height: 50px;" src="{{ asset(post.urlImagen) }}" alt="{{ post.titulo }}"></td>
                    <td>{{ post.id }}</td>
                    <td>{{ post.user.username }}</td>
                    <td>{{ post.commentCant }}</td>
                    <td>{{ post.titulo }}</td>
                    <td>{{ post.texto }}</td>
                    <td>{{ post.tipo }}</td>
                    <td>{{ post.aforo }}</td>
                    <td>{{ post.inscripciones|length }}</td>
                    <td>{{ post.fecha ? post.fecha|date('Y-m-d H:i:s') : '' }}</td>
                    <td>{{ post.visible ? 'Yes' : 'No' }}</td>
                    <td>
                        <a role="button" class="btn btn-danger espacio-pequeño" href="{{ path('post_show', {'id': post.id}) }}">Show</a>
                        <a role="button" class="btn btn-primary espacio-pequeño" href="{{ path('post_edit', {'id': post.id}) }}">Edit</a>
                        {% if app.user == post.user and post.inscripciones|length == 0 %}
                            {{ include('post/_delete_form.html.twig') }}
                        {% endif %}
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="11">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
{% endblock %}

templates/post/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Post{% endblock %}

{% block body %}
<div class="container">
    <h1>Create new Post</h1>
    <section class="blog-page">
        <div class="container">
            <div class="row">
                {% block ruta %}
                    <div class="jumbotron">
                        <div class="text-danger">
                            Show post - {{ parent() }}
                        </div>
                    </div>
                {% endblock %}
                <div class="col-sm-8">

    {{ include('post/_form.html.twig') }}

    <a href="{{ path('post_index') }}">back to list</a>

                </div>
            </div>
        </div>
    </section>
</div>
{% endblock %}

templates/post/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Post{% endblock %}
{% block body %}
    <div class="container">
        <h1>Post Details</h1>
        <section class="blog-page">
            <div class="row">
                {% block ruta %}
                    <div class="jumbotron">
                        <div class="text-danger">
                            Show post - {{ parent() }}
                        </div>
                    </div>
                {% endblock %}
                <div class="col-sm-8">
                    <div class="single-post">
                        <h1 class="venta">{{ post.titulo }}</h1>
                        <div class="blog-img venta">
                            <img src="{{ asset(post.urlImagen) }}" class="img-responsive">
                        </div>
                        <div class="row espacio">
                            <div class="alert alert-danger" role="alert">
                                You must be registered to get inscription and send message to the autor
                            </div>
                        </div>
                        {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                            {% if app.user == post.user and post.inscripciones|length == 0 %}
                                {{ include('post/_delete_form.html.twig') }}
                            {% endif %}
                            {% if app.user.id == post.user.id %}
                                <a role="button" class="btn btn-primary text-white"
                                   href="{{ path('post_edit', {'id': post.id}) }}">edit</a>
                            {% endif %}
                        {% endif %}
                        <div class="blog-meta">
                            <a href="" class="ml-0"><i
                                        class="blue-text fa fa-calendar"></i> {{ post.fecha | date("m/d/Y") }}
                            </a>
                            <a href=""><i class="blue-text fa fa-user"></i>
                                By {{ post.user.username }}</a>
                            <i class="blue-text fa fa-comment"></i> ({{ post.commentCant }})
                            Comments
                            <a href="{{ path('message_new', {'id': post.user.id}) }}"
                               class="btn btn-danger" style="color: white" id="delete"
                               role="button">Sent Message</a>
                            <a href="{{ path('inscripciones_new', {'id': post.id}) }}" style="color: white; "
                               class="btn btn-primary"
                               role="button">Inscribirse</a>
                            <a role="button" style="color: white" class="btn btn-warning text-white"
                               href="{{ path('post_index') }}">back to list</a>
                        </div>
                        <div class="text-justify">
                            {{ post.texto | raw }}
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
{% endblock %}